FROM tomcat:9-jre8-alpine
EXPOSE 8080

ADD target/benten-starter-0.1.5.war /usr/local/tomcat/webapps/benten.war


##docker build -f Dockerfile -t benten .
##docker container run -it --publish 8081:8080 benten